### ISSUE TITLE
you just put a copyright notice on code you did not write

### ISSUE THREAD

**Issue by karenetheridge** [RsrchBoy/Dist-Zilla-Plugin-ContributorsFromGit#27]
https://metacpan.org/source/RSRCHBOY/Dist-Zilla-Plugin-ContributorsFromGit-0.018/t/lib/EnsureStdinTty.pm is character-for-character identical with https://metacpan.org/source/ETHER/Dist-Zilla-Plugin-PromptIfStale-0.053/t/lib/EnsureStdinTty.pm, with the addition of a copyright notice on top.

Please do not claim copyright to code you 1. didn't write, 2. didn't give any credit for. Thank you.

**Comment by RsrchBoy** [comment]
Gah -- my apologies; I'd forgotten I have a dzil plugin that does that.  FWIW, I did credit + link in the commit message, but you're right, that is too subtle.Thanks for pointing this out, I'll fix it immediately.On Aug 13, 2017 11:46 PM, Karen Etheridge <notifications@github.com> wrote:https://metacpan.org/source/RSRCHBOY/Dist-Zilla-Plugin-ContributorsFromGit-0.018/t/lib/EnsureStdinTty.pm is character-for-character identical with https://metacpan.org/source/ETHER/Dist-Zilla-Plugin-PromptIfStale-0.053/t/lib/EnsureStdinTty.pm, with the addition of a copyright notice on top.
Please do not claim copyright to code you 1. didn't write, 2. didn't give any credit for. Thank you.
